/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.custom.dpclocker;

public final class R {
  public static final class string {
    public static final int accessibility_description=0x7f010000;
    public static final int app_name=0x7f010001;
  }
  public static final class xml {
    public static final int accessibility_service_config=0x7f020000;
  }
}